manifest:
  defaults:
    remote: zmkfirmware

  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

  projects:
    - name: zmk
      url: https://github.com/zmkfirmware/zmk.git
      revision: main
      import: app/west.yml

    - name: zmkfirmware/zap
      url: https://github.com/zmkfirmware/zap.git
      revision: main

    - path: modules/threekey_pad

  self:
    path: config
